---
title: "Cole B. Brookson - Awards"
author: "**Tel:** 613-296-0001"
date: "**Email:** cole.brookson@gmail.com"
output: pdf_document
---

-------------------     ----------------------------

## **AWARDS (A), RECOGNITION (R), & RESEARCH FUNDING (F)**

**A** - Alberta Graduate Excellence Scholarship (**12,000 CAD**), University of Alberta - 2021

**A** - Donald M. Ross Excellence Scholarship (**3,000 CAD**) - 2021

**A** - Martin J. Paetz Memorial Graduate Award in Fisheries Management (**6,100 CAD**) - 2021

**A** - Peter A. Larkin Award for Excellence in Fisheries (**400 CAD**) - 2020

**A** - NSERC Alexander Graham Bell Canada Graduate Scholarship-Masters (**17,500 CAD**) - 2020

**A** - Walter H Johns Graduate Fellowship (**5,800 CAD**), University of Alberta - 2020

**A** - Alberta Graduate Excellence Scholarship (**12,000 CAD**), University of Alberta - 2019

**A** - Thesis-Based Master’s Recruitment Scholarship (**22,990 CAD**), University of Alberta - 2019

**A** - Dept. of Biological Sciences Recruitment Scholarship (**5,000 CAD**), University of Alberta - 2019

**R** - Best Conservation & Ecology Poster (non-monetary) University of Toronto EEB Research Fair - 2019

**F** - Undergraduate Research Fund (**2,000 CAD**), University of Toronto - 2019

**A** - Conservation Essay Scholarship (**1,000 CAD**), Orca Spirit EcoTourism Co. - 2018

**A** - Edwin J. Crossman Undergraduate Scholarship (**500 CAD**), University of Toronto - 2018

**A** - Best Conservation & Ecology Poster, Runner Up (non-monetary) UofT EEB Research Fair - 2018

**A** - Jack O’Hara Memorial Forestry Scholarship (**500 CAD**), University of Toronto - 2018

**A** - Entrance Scholarship (**1,000 CAD**), University of Toronto - 2014

**A** - Entrance Scholarship (**2,000 CAD**), University of Guelph (Declined) - 2014

**A** - Entrance Scholarship (**6,000 CAD**), Trent University (Declined) - 2014
