---
title: "Cole B. Brookson"
author: "**Tel:** 613-296-0001"
date: "**Email:** cole.brookson@gmail.com"
output: pdf_document
---
## **EDUCATION**

**MSc in Ecology** (2019-2021) - 4.0 GPA
University of Alberta, Alberta, Canada  
*Supervisor:* Dr. Stephanie J. Green
*Committee:* Dr. Mark A. Lewis

**Thesis**: "Trait-based models to inform network food web rewiring under global change"

**BSc (Hons) Ecology & Evolutionary Biology** (2014-2019)
University of Toronto, Ontario, Canada
*Minor:* Environmental Biology; *Minor:* Forest Conservation Science  

* EEB499-Independent Research Project 2018-2019. *Supervisor*: Dr. Martin Krkošek. Investigating the differences in ectoparasite communities of juvenile Pacific Salmon species

* EEB397-Independent Research Project 2018-2019. *Supervisor*: Dr. Chelsea Rochman. Investigating the effects of plastic debris exposure on the population dynamics of a freshwater invertebrate, Daphnia magna

* EEB498-Independent Research Project 2017-2018. *Supervisor*: Dr. Marie-Josée Fortin. Determining the impact of climate and land cover change on beta diversity patterns on birds in Ontario

-------------------     ----------------------------

## **PUBLICATIONS**

### **In review, or revisions**

Green, S.J., **Brookson, C.B.**, Hardy, N., Crowder, L.B. (*In Review*). Trait-based approaches to global change ecology: from description to prediction, *Proceedings of the Royal Society B: Biological Sciences*

**Brookson, C.B.**, Kirk, D., Rochman, C.M. (*In Revisions*). Combining ecotoxicology and classic ecological
models to predict the effects of microplastics on the growth and viability of aquatic populations. *Ecology and
Evolution.*  

### **Published or Accepted**

Bodner, K., Rauen Firkowski, C., Bennett, J., **Brookson, C.**, Dietze, M., Green, S. ... Fortin,M.-J. (*2021*). Bridging the divide between ecological forecasts and environmental decision-making. *Ecosphere.*

Linardich, C., **Brookson, C.B.**, Green, S.J., (*2021*). Trait-based vulnerability reveals hot spots of
potential impact for a global marine invader. *Global Change Biology.* *27(18)*. 4322-4338.

**Brookson C.B.**, Krkošek, M., Hunt, B.P.V., Johnson, B.T., Rodgers, L.A., Godwin, S.C. (*2020*). Differential
infestation of juvenile Pacific salmon by parasitic sea lice in British Columbia, Canada. *Canadian Journal of
Fisheries and Aquatic Sciences.* *77(12)*, 1960-1968.

**Brookson, C.B.**, de Solla, S.J., Fernie, K.J., Cepeda, M., Rochman, C.M. (*2019*). Microplastics in the diet of
an obligate piscivore, double-crested cormorants (*Phalacrocorax auratus*), in a freshwater ecosystem.
*Canadian Journal of Fisheries and Aquatic Sciences.* *76(11)*, 2156-2163.

Rochman, C.M., **Brookson C.B.**, Bikker, J., Djuric, N., Earn, A., Bucci, K., Athey, S., ... , Borrelle, S. (*2019*).
Rethinking Microplastics as a Diverse Contaminant Suite. *Environmental Toxicology & Chemistry.* *38(4)*, 703-711.

-------------------     ----------------------------

## **TEACHING & SUPERVISION**

**Teaching Assistant, “Marine Population Ecology & Dynamics”** - Fall 2021 - Bamfield Marine Sciences Centre

Developed course materials including lectures, computer labs, and field trips alongside the course instructor, for a three-week intensive population ecology course. I also built a course website with an automatic autograder and facilitated a plan to film and edit all lectures/field trips with the purpose of putting all course content online, freely available for anyone interested.

**Undergraduate Thesis Supervision (BIOL499)** - Fall 2020/Winter 2021

Conceptualized a topic and project for an undergraduate research thesis and then supervised the completion of that thesis, assisting with timeline planning, method development, writing and presentation, and skills development. This included advising the student in statistics, programming techniques, scientific philosophy, and writing.

**Teaching Assistant, "Principles of Ecology" (BIOL208)** - Winter 2021

Ran lab sections for 12 separate sections of students, instructing on general ecological principles as well as specific lab skills. Grading responsibilities included marking >80 final lab reports.

**Instructor, Workshop Series: "Reproducible Methods for Biological Research"** - Spring 2021

Developed content and individual lesson plans for a 7-week workshop series introducing graduate students and professionals to methods for making biological research reproducible. Instruction was given on the use of version control (i.e. Git/GitHub), script management, container software (i.e. Docker, Singularity), parallel computing, distributed computing, and cloud computing.

**Instructor, Workshop Series: "Introduction to Programming in R/RStudio for Biology"** - Winter 2019 & Fall 2020

Developed content and individual lesson plans for a 5-week workshop to teach undergraduate students tools for data management and manipulation, best practices in script management, foundational programming skills, and data visualization. Delivered and co-taught a mixed asynchronous/synchronous remote lecture mixture to accommodate students. Built and maintained a website for course website. Created stand-alone reference documents and live-coded videos for the series.

**Instructor, Workshop Series: "Introduction to Programming in Python for Biology"** - Fall 2020

Developed content and individual lesson plans for a 5-week workshop to teach undergraduate students tools for data management and manipulation, best practices in script management, foundational programming skills, and data visualization in Python. Delivered and co-taught a mixed asynchronous/synchronous remote lecture mixture to accommodate students. Built and maintained a website for course website. Created stand-alone reference documents and live-coded videos for the series.

-------------------     ----------------------------

## **AWARDS (A), RECOGNITION (R), & RESEARCH FUNDING (F)**

**A** - D Alan Birdsall Memorial Scholarship (**7,000 CAD**), University of Alberta - 2022

**A** - Alberta Graduate Excellence Scholarship (**12,000 CAD**), University of Alberta - 2021

**A** - Donald M. Ross Excellence Scholarship (**3,000 CAD**) - 2021

**A** - Martin J. Paetz Memorial Graduate Award in Fisheries Management (**6,100 CAD**) - 2021

**A** - Peter A. Larkin Award for Excellence in Fisheries (**400 CAD**) - 2020

**A** - NSERC Alexander Graham Bell Canada Graduate Scholarship-Masters (**17,500 CAD**) - 2020

**A** - Walter H Johns Graduate Fellowship (**5,800 CAD**), University of Alberta - 2020

**A** - Alberta Graduate Excellence Scholarship (**12,000 CAD**), University of Alberta - 2019

**A** - Thesis-Based Master’s Recruitment Scholarship (**22,990 CAD**), University of Alberta - 2019

**A** - Dept. of Biological Sciences Recruitment Scholarship (**5,000 CAD**), University of Alberta - 2019

**R** - Best Conservation & Ecology Poster (non-monetary) University of Toronto EEB Research Fair - 2019

**F** - Undergraduate Research Fund (**2,000 CAD**), University of Toronto - 2019

**A** - Conservation Essay Scholarship (**1,000 CAD**), Orca Spirit EcoTourism Co. - 2018

**A** - Edwin J. Crossman Undergraduate Scholarship (**500 CAD**), University of Toronto - 2018

**A** - Best Conservation & Ecology Poster, Runner Up (non-monetary) UofT EEB Research Fair - 2018

**A** - Jack O’Hara Memorial Forestry Scholarship (**500 CAD**), University of Toronto - 2018

**A** - Entrance Scholarship (**1,000 CAD**), University of Toronto - 2014

**A** - Entrance Scholarship (**2,000 CAD**), University of Guelph (Declined) - 2014

**A** - Entrance Scholarship (**6,000 CAD**), Trent University (Declined) - 2014

-------------------     ----------------------------

## COMMUNITY AND LEADERSHIP

**Ecological Society of America Council - Student Representative (Jan 2022 - Dec 2024)**

The ESA Council is a representative body that includes leadership from the disciplinary and geographic units and reflects the diversity of ESA’s members. I represent the student section to the council, and promote student participation in advancing ESA's mission. 

**Diversity, Equity, & Inclusion Committee Member - Society for Open and Reproducible Ecology & Evolution (Dec 2021 - Present)**

The DEI committee focuses on advancing SORTEE's mission to make science a more equitable place. My role is as the consultant to the Membership Committee, helping to identify groups that are not equitably represented in the membership, and make recommendations to the membership committee. 

**Advocacy Committee Member - Society for Open and Reproducible Ecology & Evolution (Dec 2021 - Present)**

I work as a project drafter for the committee, identifying projects to promote and advocate for open science initiatives within the Society and more broadly. 

**Education & Outreach Committee Member - Society for Open and Reproducible Ecology & Evolution** (Sept 2020 - Present)

This committee focuses on directing outreach and education initiatives towards members of the scientific community to promote open and accessible research in ecology and evolution. I contribute to program development, annual meeting programming, and developing online resources.

**Courses & Curriculums Committee Member - Dept. of Biological Sciences, UAlberta** (Sept 2020 - May 2021)

Served on committee that oversees and directs the course offerings in the department of Biological Sciences at the University of Alberta. I reviewed proposed course and curricula changes, and provided feedback and development of program development overall.

**Graduate Student Peer Tutor - First Peoples House, UAlberta** (Nov 2019 - May 2020)

Tutored fellow graduate students in the Department of Biological Sciences, in computing science, statistics, and ecological modeling.

**Graduate Student Organizer - Quantitative Ecology Group, UAlberta** (Sept 2019 - May 2020)

Initiated and organized a bi-weekly meeting of quantitative ecologists for discussions surrounding methods, best practices, and general ideas in mathematical and statistical ecology.

**Outreach Scientist - Skype a Scientist Foundation** (Oct 2019 - Present)

Volunteered as an outreach ambassador, using Skype to connect with classrooms worldwide to speak to children about aquatic/marine ecology and my work as a researcher.

**RE Peter Biological Science Conference Organizing Committee Member - UAlberta** (Sept 2019 - March 2020)

Acted as a committee member in charge of planning, logistics, speaker liaising, and execution of the RE Peter Conference, an annual conference in the department.

**Student Mentor & Tutor - Golden Mentors** (Sept 2019 - April 2020)

Volunteered tutoring high school students in mathematics, biology, calculus, and computer programming.

**Atwood Colloquium Organizer - UToronto** (April 2018 & 2019)

Various logistics for the departmental in-house conference (prepare refreshments, set up and tear down conference venue).

**Student Experience Mentor - UToronto Student Experience Mentorship Program** (Feb 2019 - April 2019)

Acted as a mentor to a member of the University of Toronto’s Student Life staff, helping to bridge the gap between students and staff/faculty and providing insight on the student experience at U of T and how it could be improved.

**Undergraduate Peer Mentor - UToronto Ecology & Evolutionary Biology Peer Mentorship Program** (Sept 2018 - April 2019)

Mentored two 2 nd year undergraduate students, advising them on course selection, gaining research experience, and getting the most out of their undergraduate experience. Additionally, acted as an ambassador for potential members of the program, and promoted it within the university.

**Student Facilitator - UToronto Ecology & Evolutionary Biology Conservation Sub-group** (Sept 2018 - April 2018)

Participated in discussions and facilitated community partnerships with local outreach initiatives to promote public awareness of conservation issues and support citizen science.

**Undergraduate Evaluation Faculty Search Committee Group Member - UToronto Ecology & Evolutionary Biology Dept.** (Nov 2018)

Assisted with the review process of tenure-track applications for a teaching stream faculty member in the department of Ecology & Evolutionary Biology.

**Outreach Team Member - UofT Trash Team** (Sept 2018 - April 2020)

Develop and present education outreach material about plastic pollution problems and solutions to groups of interested community groups.

**Outreach Program Leader - Ontario BioBlitz** (May 2018)

Developed and presented educational outreach material about plastic pollution to members of the public and members of the BioBlitz team.

**Treasurer - UToronto Forestry Undergraduate Student Union** (Sept 2017 - 2018)

Maintained a balanced budget for a student-run, not-for-profit group.

-------------------     ----------------------------

## ADDITIONAL RESEARCH EXPERIENCE

**Research Assistant** (May 2019 - Aug 2019)  
Supervisor: Dr. Stephanie Green  
Dept. of Biological Sciences, University of Alberta  

* Performed data management and constructed ecological models to determine vulnerability of various prey species to an invasive predator
* Assisted with a review of all relevant literature surrounding traits-based foraging ecology

**Data Analyst Research Assistant** (Feb 2019 - April 2019)  
Supervisor: Dr. Marie-Josée Fortin  
Dept. of Ecology & Evolutionary Biology, University of Toronto

* Assisted with spatial analysis and data management for a long-term ecological monitoring project
* Performed data wrangling and cleaning tasks for large ecological datasets

**Work-Study Student** (Sept 2018 - Feb 2019)
Supervisor: Dr. Marie-Josée Fortin
Dept. of Ecology & Evolutionary Biology, University of Toronto

* Assisted with spatial analysis of ecological and oceanographic data to inform Marine Protected Area
design

**Research Assistant** (Oct 2017 - Sept 2018)
Supervisor: Dr. Chelsea Rochman
Dept. of Ecology & Evolutionary Biology, University of Toronto

* Conducted multiple lab studies on incidence of microplastics in aquatic ecosystems

**Volunteer Research Assistant** (March 2018 – July 2018) 
Supervisor: Dr. Benjamin Gilbert (Kaitlyn Brown) 
Department of Ecology & Evolutionary Biology, University of Toronto
* Assisted with data collection and analysis for a community ecology experiment examining the effects of species assemblage on plant fitness
* Managed other undergraduate assistants and coordinated data collection

**Volunteer Research Assistant** (Sept. 2017 – July 2018) 
Supervisor: Dr. Luke Mahler (Christopher Boccia) 
Department of Ecology & Evolutionary Biology, University of Toronto
* Performed morphometric landmark analysis and data management and manipulation to investigate how adaptive traits can be used to build an Anolis lizard phylogeny 

**Work-Study Student** (Sept. 2017 – Feb. 2018) 
Supervisor: Dr. Benjamin Gilbert (Denon Start) 
Department of Ecology & Evolutionary Biology, University of Toronto, ON
* Assisted with data collection and analysis for a community ecology experiment looking at the effects of species assemblage on plant fitness

**Field Research Assistant** (May 2017 – Sept. 2017) 
Supervisor: Dr. Spencer Barrett (David Timerman)
University of Toronto – Koffler Scientific Reserve at Jokers Hill, Newmarket, ON
* Assisted with experimental design, set-up and management of a study looking at the reproductive responses to sex ratio treatments
* Conducted data entry and management tasks including organizing and analyzing large datasets

**Volunteer Lab Assistant** (Sept. 2016 – April 2017) 
Supervisor: Dr. Spencer Barrett (David Timerman/Chris Balogh) 
Department of Ecology & Evolutionary Biology, University of Toronto, ON
* Assisted with greenhouse and lab duties related to maintaining plant stocks and data collection 
* Performed data analysis and management tasks for a variety of experimental datasets

-------------------     ----------------------------

## ACADEMIC SERVICE

*Manuscript reviewer for:* Conservation Biology, Journal of Fish Biology, Proceedings of the Royal Society; Biology, PCI Computational Biology 

*Professional societies:*

Canadian Society for Ecology & Evolution (CSEE)

Ecological Society of America (ESA)

American Fisheries Society (AFS)

Society for Open and Reproducible Ecology & Evolution (SORTEE)

-------------------     ----------------------------

## PRESENTATIONS

***NOTE***: *Italic* font indicates invited speaker.

***American Fisheries Associated Annual Meeting - Online*** (Sept 2020)
“A trait-based approach to predicting predator-prey dynamics under climate change”

***Canadian Society for Ecology &amp; Evolution Annual Meeting – Edmonton, Canada** (May 2020)
“Prey-switching as a method of persistence for predatory species under climate change”
  *Cancelled due to SARS-CoV-2

**North Pacific Maine Science Organization Annual Meeting (PICES) – Victoria, Canada** (Oct 2019)
“A trait-based approach to predicting predator-prey uncoupling under climate change”

**Ocean Awareness Symposium - David Thomas King School, Edmonton, Canada** (Oct 2019)
“Living in the Bath Tub – Climate Change and the Effects on our Ocean Ecosystems”

**Canadian Society for Ecology &amp; Evolution Annual Meeting – Fredericton, Canada** (Aug 2019)
“A combined ecotoxicological and classical ecological modeling approach predicts microplastics may be
affecting the growth and viability of Daphnia Magna populations in aquatic ecosystems”

**University of Toronto EEB Undergraduate Research Fair - Toronto, Canada** (April 2019)
“Differential Infection of Juvenile Pacific Salmon by Parasitic Sea Lice”

**University of Toronto Undergraduate Research Conference - Toronto, Canada** (Jan 2019)
“Microplastics in the diet of an obligate piscivore, double-crested cormorants (*Phalacrocorax auratus*), in a freshwater ecosystem”

**International Science Day - John Fraser SS, Toronto, Canada** (Nov 2018)
“What’s in the Water? Aquatic Ecology &amp; Ecosystem Conservation in the Age of Plastic”

**University of Toronto EEB Undergraduate Research Fair - Toronto, Canada** (April 2018)
“The Effects of Climate and Land Use Change on Beta Diversity of Breeding Birds in Southern Ontario.”

**Earth Day Symposium – Humberside CI, Toronto, Canada** (March 2018)
“Plastic Pollution in Aquatic Ecosystems”

-------------------     ----------------------------

## SKILLS & CERTIFICATIONS

Proficient use of Fourier Transform Infrared Spectroscopy (FTIR, Bruker 2018) technologies

Fluent use of R, Python, Julia, MATLAB, and ArcGIS software, experience with C/C++, Mathematica, Java, JavaScript, and RShiny

Ontario ‘G’ Licence (Ontario Ministry of Transportation, 2017), Pleasure Craft Operator Card (Transport Canada, 2018), Standard First Aid & CPR / AED Level C (Red Cross, 2015)

Diversity Practitioner (National Diversity Council 2018), SmartServe Certification (Liquor Control Board of Ontario, 2015)
