# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cole Brookson
email: cole.brookson@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Website for personal research, teaching, and software tutorials.
twitter_username: cole_brookson
github_username: colebrookson
minimal_mistakes_skin: contrast
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

footer:
  links:

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

defaults:
  # _sessions
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      sidebar:
        nav: "sessions"


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


# Site Author
author:
  name: "Cole B. Brookson"
  avatar: "/assets/images/cole.jpg"
  bio: "University of Alberta \n
        Dept. of Biological Sciences"
  location: "Toronto, ON "
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:cole.brookson@gmail.com
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/colebrookson/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/cole_brookson"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/cole-brookson/"
    - label: "Research Gate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/Cole_Brookson"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/cole_brookson"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/colebrookson"
